### ISSUE TITLE
Renaming Profile/Scenario makes Easer Crash

### ISSUE THREAD

**Issue by qoheniac** [renyuneyun/Easer#106]
Renaming a profile or scenario that is used in a script makes Easer crash. After that it crashes every time I open it. I fixed it by reinstalling it and assure the profile or scenario I want to rename is not used.

**Comment by churib** [comment]
I can confirm that, had the same issue and solved it also by reinstalling.

BTW: Thanks for the great work!

**Comment by renyuneyun** [comment]
I identified some (maybe) relevant bugs of Condition, and fixed in 59338a30e5f245c8fbff2d0a385224cb5e407793 and a2e4f3043e9b0f99e8fc78b5c0dcfc3fe65955fa .

Actually I don't see why renaming Profile or Scenario makes Easer crash, because that has been resolved long ago. Neither could I reproduce it actually.
Could you provide a detailed step or screencast / screen recording?

**Comment by qoheniac** [comment]
I just did a bit of testing and renaming of profiles isn't a problem (sorry for claiming this above). But renaming of used scenarios makes Easer crash every time! Here a simple step-by-step example:

0. Install Easer 0.6 from F-Droid, grant permissions and make it run.
1. Create a scenario named foo (Time 6:00)
2. Create a script named bar that uses foo as a scenario and leave everything else blank.
3. Change the name of the scenario foo to test.

After hitting save Easer crashes with the message "Unfortunately, Easer has stopped." and then crashes every time I try to start it with that same message.

**Comment by wangongtsen** [comment]
Following qoheniac's steps, I can recreate the crash. But it occurs as soon as I open the script _bar_ to edit it. App restarts normally and you can resolve the problem by deleting the script _bar_. Not as bad, but still not ideal.

easer v0.6.5
LineageOS v14.1

**Comment by renyuneyun** [comment]
@wangongtsen Thanks for reporting. I can confirm the bug, but not yet sure where in the logic made this happen. (The behaviour is that the *bar* script still points to *foo*, rather than *test*.)
Anyway, I'll fix this as soon as I figure it out.

**Comment by wangongtsen** [comment]
Can't you resolve this by using an identifier, that can't be changed (or even seen) by the user like a number?

**Comment by renyuneyun** [comment]
Whoops, forgot to mention: this should have been solved in v0.6.6 (which
will appear in the repo a few days later because of fdroid build process).

Yes, using an identifier is a feasible solution, but I'd prefer not to use
it for now. The current way of handling storage is quite naive, and I'm
thinking of changing it to a better way. I'm planning to use identifier
after that.

wangongtsen <notifications@github.com> 于 2018年6月16日周六 20:44写道：

**Comment by renyuneyun** [comment]
I'm closing this as it should have been fixed (?).

Feel free to reopen it :)
